import type { Metadata } from "next";
import "./globals.css";
import {
  Google_Sans_Flex,
  DM_Sans,
  Outfit,
  Manrope,
  Inter } from "next/font/google";
import { cn } from "@/lib/utils";
import Script from "next/script";


const preset1 = Google_Sans_Flex({
  subsets: ["latin"],
  variable: "--font-preset-1",
});
const preset2 = DM_Sans({ subsets: ["latin"], variable: "--font-preset-2" });
const preset3 = Outfit({ subsets: ["latin"], variable: "--font-preset-3" });
const preset4 = Manrope({ subsets: ["latin"], variable: "--font-preset-4" });
const preset5 = Inter({ subsets: ["latin"], variable: "--font-preset-5" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const THEME_INIT_SCRIPT = `
(function() {
  try {
    var stored = localStorage.getItem('tushe-theme');
    var theme = stored || (window.matchMedia('(prefers-color-scheme: dark)').matches ? 'Dark' : 'Light');
    document.documentElement.setAttribute('data-theme', theme);
  } catch (e) {}
})();
`;

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      data-accent="tushe"
      data-neutral="Mauve"
      data-radius="dafault"
      data-font="preset-5"
      suppressHydrationWarning
      className={cn("h-full", "antialiased", preset1.variable, preset2.variable, preset3.variable, preset4.variable, preset5.variable, "font-sans")}
    >

      <body className="min-h-full flex flex-col">
        <Script id="theme-init" strategy="beforeInteractive">
  {THEME_INIT_SCRIPT}
</Script>
        {/* <ThemeToggle /> */}
        {children}
      </body>
    </html>
  );
}
